/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FormIndex;

/**
 *
 * @author Muhammad Nibras A. A
 */
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class InterfaceForm extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    Connection koneksi = KoneksiDatabase.database.bukaKoneksi();
    
    public InterfaceForm() {
        initComponents();
        showData();
    }

    private void tableCleaning(){
        textNamaPasien.setText("");
        textAlamatPasien.setText("");
        textLahirPasien.setText("");
        textTelpPasien.setText("");
        
        buttonSimpan.setText("Simpan");
        textNamaPasien.setEditable(true);
    }
    
        private void cariData(){
            try {
                st = koneksi.createStatement();
                rs = st.executeQuery("SELECT * FROM identifikasi WHERE `" 
                        + comboCari.getSelectedItem().toString() + 
                        "` LIKE '%" + textCari.getText() + "%'");

                DefaultTableModel model = new DefaultTableModel();
                model.addColumn("No.");
                model.addColumn("Nama Lengkap");
                model.addColumn("Jenis Kelamin");
                model.addColumn("Alamat Rumah");
                model.addColumn("Tanggal Lahir");
                model.addColumn("Nomor Telepon");

                int no = 1;

                model.getDataVector().removeAllElements();
                model.fireTableDataChanged();
                model.setRowCount(0);
                tabelData.setModel(model);

                while (rs.next()) {
                    Object[] data = {
                        no ++,
                        rs.getString("Nama Lengkap"),
                        rs.getString("Jenis Kelamin"),
                        rs.getString("Alamat Rumah"),
                        rs.getString("Tanggal Lahir"),
                        rs.getString("Nomor Telepon")
                    };
                    model.addRow(data); 
                }

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error" + e.getMessage());
            }
        }

        private void showData(){
            try {
                st = koneksi.createStatement();
                rs = st.executeQuery("SELECT * FROM identifikasi");

                DefaultTableModel model = new DefaultTableModel();
                model.addColumn("No.");
                model.addColumn("Nama Lengkap");
                model.addColumn("Jenis Kelamin");
                model.addColumn("Alamat Rumah");
                model.addColumn("Tanggal Lahir");
                model.addColumn("Nomor Telepon");

                int no = 1;

                model.getDataVector().removeAllElements();
                model.fireTableDataChanged();
                model.setRowCount(0);

                while (rs.next()) {
                    Object[] data = {
                        no ++,
                        rs.getString("Nama Lengkap"),
                        rs.getString("Jenis Kelamin"),
                        rs.getString("Alamat Rumah"),
                        rs.getString("Tanggal Lahir"),
                        rs.getString("Nomor Telepon")
                    };
                    model.addRow(data);
                    tabelData.setModel(model);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textAlamatPasien = new javax.swing.JTextField();
        textLahirPasien = new javax.swing.JTextField();
        textTelpPasien = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        buttonSimpan = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonBatal = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        comboCari = new javax.swing.JComboBox<>();
        textCari = new javax.swing.JTextField();
        textNamaPasien = new javax.swing.JTextField();
        buttonLaki = new javax.swing.JRadioButton();
        buttonPerempuan = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Data Pasien Rumah Sakit Unmer Malang");
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(1280, 720));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setText("Data Identifikasi Pasien");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Nama Lengkap");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("Jenis Kelamin");

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("Tanggal Lahir");

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setText("Alamat Rumah");

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setText("Nomor Telepon");

        textAlamatPasien.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        textLahirPasien.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        textTelpPasien.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        tabelData.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama Lengkap", "Jenis Kelamin", "Alamat Rumah", "Tanggal Lahir", "Nomor Telepon"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelData.setShowGrid(true);
        tabelData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelData);

        buttonSimpan.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonHapus.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonBatal.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        buttonBatal.setText("Batal");
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setText("Cari Data");

        comboCari.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        comboCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama Lengkap", "Jenis Kelamin", "Tanggal Lahir", "Alamat Rumah", "Nomor Telepon" }));

        textCari.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textCariKeyPressed(evt);
            }
        });

        textNamaPasien.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        buttonLaki.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        buttonLaki.setText("Laki-Laki");

        buttonPerempuan.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        buttonPerempuan.setText("Perempuan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textAlamatPasien)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(textLahirPasien, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textTelpPasien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                                    .addComponent(comboCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(textCari, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonLaki, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonPerempuan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(361, 361, 361)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(49, 49, 49)
                        .addComponent(textNamaPasien)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(textNamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(buttonLaki)
                                    .addComponent(buttonPerempuan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textAlamatPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textLahirPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textTelpPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonSimpan)
                            .addComponent(buttonHapus)
                            .addComponent(buttonBatal))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        // TODO add your handling code here:
        tableCleaning();
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        try {
            st = koneksi.createStatement();
            if (textNamaPasien.getText().equals("") || 
                    textAlamatPasien.getText().equals("") || 
                    textLahirPasien.getText().equals("") ||
                    textTelpPasien.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Data tidak diperbolehkan kosong", "Validasi Data", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if (!buttonLaki.isSelected() && !buttonPerempuan.isSelected()) {
            JOptionPane.showMessageDialog(null, "Pilih Jenis Kelamin Pasien", "Validasi Data", JOptionPane.INFORMATION_MESSAGE);
            return;
            }
            
            if (buttonSimpan.getText() == "Simpan") {
                String cek = "SELECT * FROM identifikasi WHERE `Nama Lengkap` = '" + textNamaPasien.getText() + "'";
                rs = st.executeQuery(cek);
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Nama pasien ini sudah terdaftar");
                } else {
                    String selectedOption = buttonLaki.isSelected() ? "Laki-Laki" : (buttonPerempuan.isSelected() ? "Perempuan" : "");
                    
                    String sql = "INSERT INTO identifikasi VALUES ('" + textNamaPasien.getText() + 
                            "','" + selectedOption +
                            "','" + textAlamatPasien.getText() +
                            "','" + textLahirPasien.getText() +
                            "','" + textTelpPasien.getText() + "')";
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data telah berhasil disimpan");
                    tableCleaning();
                    showData();
                }
            } else {
                //Pemicu pengubahan data
                String selectedOption = buttonLaki.isSelected() ? "Laki-Laki" : (buttonPerempuan.isSelected() ? "Perempuan" : "");
                String update = "UPDATE identifikasi SET `Jenis Kelamin` = '" + selectedOption +
                        "', `Nomor Telepon` = '" + textTelpPasien.getText() +
                        "', `Alamat Rumah` = '" + textAlamatPasien.getText() +
                        "', `Tanggal Lahir` = '" + textLahirPasien.getText() +
                        "' WHERE `Nama Lengkap` = '" + textNamaPasien.getText() + "'";
                st.executeUpdate(update);
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                tableCleaning();
                showData();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void tabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataMouseClicked
        // TODO add your handling code here:
        textNamaPasien.setText(tabelData.getValueAt(tabelData.getSelectedRow(), 1).toString());
        textAlamatPasien.setText(tabelData.getValueAt(tabelData.getSelectedRow(), 3).toString());
        textLahirPasien.setText(tabelData.getValueAt(tabelData.getSelectedRow(), 4).toString());
        textTelpPasien.setText(tabelData.getValueAt(tabelData.getSelectedRow(), 5).toString());
        
        String selectedRadioButton = tabelData.getValueAt(tabelData.getSelectedRow(), 2).toString();
        if ("Laki-Laki".equals(selectedRadioButton)) {
            buttonLaki.setSelected(true);
            buttonPerempuan.setSelected(false);
        } else if ("Perempuan".equals(selectedRadioButton)) {
            buttonLaki.setSelected(false);
            buttonPerempuan.setSelected(true);
        }
        
        textNamaPasien.setEditable(false);
        buttonSimpan.setText("Ubah");
    }//GEN-LAST:event_tabelDataMouseClicked

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        if (textNamaPasien.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih data yang akan dihapus!");
        } else {
            int Jawaban = JOptionPane.showConfirmDialog(null, "Data ini akan dihapus, Tekan Yes untuk lanjutkan", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (Jawaban == 0) {
                try {
                    st = koneksi.createStatement();
                    String jenis = buttonLaki.isSelected() ? "Laki-Laki" : "Perempuan";
                    
                    String sql = "DELETE FROM identifikasi WHERE `Nama Lengkap` = '" + textNamaPasien.getText() + "' AND `Jenis Kelamin` = '" + jenis + "'";
                    
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                    showData();
                    tableCleaning();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error");
                }
            }
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void textCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCariKeyPressed
        // TODO add your handling code here:
        cariData();
    }//GEN-LAST:event_textCariKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBatal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JRadioButton buttonLaki;
    private javax.swing.JRadioButton buttonPerempuan;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JComboBox<String> comboCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelData;
    private javax.swing.JTextField textAlamatPasien;
    private javax.swing.JTextField textCari;
    private javax.swing.JTextField textLahirPasien;
    private javax.swing.JTextField textNamaPasien;
    private javax.swing.JTextField textTelpPasien;
    // End of variables declaration//GEN-END:variables
}
